name: chatty
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  agora_rtc_engine: ^6.1.0
  cached_network_image: ^3.2.0
  cloud_firestore: ^4.4.5
  cloud_firestore_odm: ^1.0.0-dev.52
  cookie_jar: ^3.0.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  device_info: ^2.0.3
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  dots_indicator: ^2.1.0
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  firebase_in_app_messaging: ^0.7.0+8
  firebase_messaging: ^14.1.4
  firebase_storage: ^11.0.8
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_cupertino_localizations: ^1.0.1
  flutter_easyloading: ^3.0.3
  flutter_local_notifications: ^13.0.0
  flutter_screenutil: ^5.3.1
  flutter_spinkit: ^5.1.0
  flutter_verification_code: ^1.1.6
  fluttertoast: ^8.0.9
  get: ^4.6.5
  google_sign_in: ^5.3.3
  image_picker: ^0.8.6
  intl: ^0.17.0
  just_audio: ^0.9.30
  loading_animations: ^2.2.0
  location: ^4.4.0
  package_info: ^2.0.2
  path_provider: ^2.0.9
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  pull_to_refresh: ^2.0.0
  sentry: ^6.3.0
  share: ^2.0.4
  shared_preferences: ^2.0.13
  sqflite: ^2.0.3+1
  uni_links: ^0.5.1
  webview_flutter: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/Sound_Horizon.mp3
    - assets/audio_mixing/Agora.io-Interactions.mp3
    - assets/agora-logo.png
    - assets/dang.mp3
    - assets/ding.mp3
    - assets/gif.gif
    - assets/jpg.jpg

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400 # normal
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
