// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Fs5k3B6lq2NVbZQm7TI-VpC3qAWR2lU',
    appId: '1:188505231406:android:6d51b32bf09661f3fb8fbf',
    messagingSenderId: '188505231406',
    projectId: 'flutter-video-audio-chat-5280c',
    storageBucket: 'flutter-video-audio-chat-5280c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5JMTAfuPc2WDjo5yqMGwml4Q8nt1B-nA',
    appId: '1:188505231406:ios:3abf8fda2c7111f7fb8fbf',
    messagingSenderId: '188505231406',
    projectId: 'flutter-video-audio-chat-5280c',
    storageBucket: 'flutter-video-audio-chat-5280c.appspot.com',
    iosClientId: '188505231406-an25jvs31cr94k0brrjtte59hrj3hmop.apps.googleusercontent.com',
    iosBundleId: 'com.dbestech.chatty',
  );
}
